trailer_rental/towit/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from towit.views import *
from towit.view.tracker import (
    trackers,
    tracker_data, TrackerCreateView,
    TrackerUpdateView,
    tracker_detail_n, delete_tracker,
    trackers_data,
    get_tracker_data,
    tracker_upload,
    get_tracker_upload,
    tracker_detail,
    tracker_export,
    tracker_debug,
    debug_detail,
    trackers_table)

urlpatterns = [
    # Entry point
    path('', dashboard, name='dashboard'),
    path('dashboard/',  dashboard, name='dashboard'),
    # Trailer
    path('new_trailer/',  TrailerCreateView.as_view(), name='new_trailer'),
    path('update_trailer/<slug:pk>',
         TrailerUpdateView.as_view(), name='update_trailer'),
    path('trailers/',  trailers, name='trailers'),
    path('trailer/<int:id>',  trailer_detail, name='trailer_detail'),
    path('delete_trailer/<int:id>',  delete_trailer, name='delete_trailer'),
    path('trailer_json/<int:id>',  trailer_json, name='trailer_json'),
    # Maintenance
    path('new_maintenance/<int:trailer_id>',
         MaintenanceCreateView.as_view(), name='new_maintenance'),
    path('update_maintenance/<slug:pk>',
         MaintenanceUpdateView.as_view(), name='update_maintenance'),
    path('maintenances/<int:trailer_id>',  maintenances, name='maintenances'),
    # Trailer pictures
    path('new_picture/<int:trailer_id>',
         TrailerPictureCreateView.as_view(), name='new_picture'),
    path('share_images/<ids>',  share_images, name='share_images'),
    path('delete_trailer_images/<ids>',
         delete_trailer_images, name='delete_trailer_images'),
    # Contacts
    path('new_contact/',  ContactCreateView.as_view(), name='new_contact'),
    path('contact/<int:id>',  contact_detail, name='contact_detail'),
    path('update_contact/<slug:pk>',
         ContactUpdateView.as_view(), name='update_contact'),
    path('contacts/',  contacts, name='contacts'),
    # Lessee
    path('new_lessee/<int:contact_id>',  LesseeCreateView.as_view(),
         name='new_lessee_from_contact'),
    path('new_lessee/trailer/<int:trailer_id>',
         LesseeCreateView.as_view(), name='new_lessee_from_trailer'),
    path('new_lessee/',  LesseeCreateView.as_view(), name='new_lessee'),
    # Contracts
    path('new_contract/<int:lessee_id>/',
         LeaseCreateView.as_view(), name='new_contract'),
    path('contract/<int:id>',  contract_detail, name='contract_detail'),
    path('contract_signed/<int:id>',  contract_detail_signed,
         name='contract_detail_signed'),
    path('upload_contract_document/<int:id>',
         ContractDocumentCreateView.as_view(), name='upload_contract_document'),
    path('contracts/',  contracts, name='contracts'),
    path('update_contract/<slug:pk>',
         ContractUpdateView.as_view(), name='update_contract'),
    path('delete_contract/<slug:id>',  delete_contract, name='delete_contract'),
    path('change_contract_stage/<slug:id>/<int:stage>',
         change_contract_stage, name='change_contract_stage'),
    path('capture_signature/<int:lease_id>/<position>',
         HandWritingCreateView.as_view(), name='capture_signature'),
    # Tracker
    path('new_tracker/<int:trailer_id>',
         TrackerCreateView.as_view(), name='new_tracker'),
    path('update_tracker/<slug:pk>',
         TrackerUpdateView.as_view(), name='update_tracker'),
    path('delete_tracker/<int:id>',  delete_tracker, name='delete_tracker'),
    path('tracker_detail/<int:id>',  tracker_detail, name='tracker_detail'),
    path('tracker_detail/<int:id>/<int:n>',
         tracker_detail_n, name='tracker_detail_n'),
    path('trackers_map/',  trackers, name='trackers'),
    path('trackers/',  trackers_table, name='trackers_table'),
    path('trackers_map/data', trackers_data, name='trackers_json'),
    path('tracker_data', tracker_data, name='tracker_data'),
    path('get_tracker_data/<int:id>', get_tracker_data, name='get_tracker_data'),
    path('tracker_debug', tracker_debug, name='tracker_debug'),
    path('debug_detail/<int:id>',  debug_detail, name='debug_detail'),
    path('upload_data', tracker_upload, name='upload_data'),
    path('get_upload_data/<int:id>', get_tracker_upload, name='get_upload_data'),
    path('tracker_export/<int:id>', tracker_export, name='tracker_export'),
]

trailer_rental/trailer_rental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('contracts/', include('contracts.urls')),
    path('towit/', include('towit.urls')),
]

trailer_rental/towit/models.py
from django.db import models
from datetime import datetime
from gdstorage.storage import GoogleDriveStorage
from django.urls import reverse
from django.contrib.auth.models import User

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

class UserProfile(models.Model):
    user   = models.OneToOneField(User,
                        on_delete=models.CASCADE,
                        related_name='profile_user')
    avatar = models.ImageField(upload_to='avatars')
    # avatar = models.ImageField(upload_to='towit/avatars', storage=gd_storage)
    def __str__(self):
        return self.user.get_username()

class Owners(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=7, blank=True)
    
    def __str__(self):
        return self.name
    
class TrailerType(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Status(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Interest(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class LeaseStage(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class MaintenanceStatus(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Stage(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Trailer(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(TrailerType,
                            on_delete=models.CASCADE,
                            related_name='trailer_type')
    vin = models.CharField(max_length=50)
    year = models.DateField(default=datetime.now().strftime(("%Y")))
    size = models.IntegerField()
    number_of_axles = models.PositiveSmallIntegerField(
        choices=((1,'2'),
                (2,'3')),
        default=1,
    )
    color = models.ForeignKey(Color,
                            on_delete=models.CASCADE,
                            related_name='trailer_color')
    status = models.ForeignKey(Status,
                            on_delete=models.CASCADE,
                            default = 1,
                            related_name='trailer_status')
    bed_type = models.PositiveSmallIntegerField(
        choices=((1,'Wood'),
                (2,'Steel')),
        default=1,
    )
    bed_comments = models.TextField(blank=True)
    current_tires_condition = models.PositiveSmallIntegerField(
        choices=((1,'100%'),
                (2,'75%'),
                (3,'50%')),
        default=1,
    )
    tire_layers = models.PositiveSmallIntegerField(
        choices=((1,'10'),
                (2,'14'),
                (3,'16')),
        default=1,
    )
    has_spare_tire = models.PositiveSmallIntegerField(
        choices=((1,'Yes'),
                (2,'No')),
        default=1,
    )
    number_of_ramps = models.IntegerField()
    ramps_material = models.PositiveSmallIntegerField(
        choices=((1,'Aluminium'),
                (2,'Steel')),
        default=1,
    )
    ramps_length = models.PositiveSmallIntegerField(
        choices=((1,'5'),
                (2,'6'),
                (3,'7'),
                (4,'8'),
                (5,'9')),
        default=1,
    )
    electrical_instalation = models.TextField(blank=True)
    price = models.IntegerField()
    tax_price = models.IntegerField()
    tax = models.PositiveSmallIntegerField(
        choices=((1,6.25),
                (2,8.5)),
        default=1,
    )
    owner = models.ForeignKey(Owners,
                            on_delete=models.CASCADE,
                            related_name='trailer_owner')
    Legal_owner = models.ForeignKey(Owners,
                            on_delete=models.CASCADE,
                            related_name='trailer_legal_owner')
    plate = models.CharField(max_length=50)
    plate_stage = models.PositiveSmallIntegerField(
        choices=((1,'Temporary'),
                (2,'Permanent')),
        default=1,
    )
    plate_file = models.FileField(upload_to='towit/plates', blank=True, 
                                  storage=gd_storage) 
    title = models.ForeignKey(Stage,
                            on_delete=models.CASCADE,
                            related_name='title_stage')
    # title_file = models.FileField(upload_to='titles', blank=True)
    title_file = models.FileField(upload_to='towit/titles', blank=True, 
                                  storage=gd_storage)
    title_note = models.TextField(blank=True)
    sticker = models.ForeignKey(Stage,
                            on_delete=models.CASCADE,
                            related_name='sticker_stage')
    # sticker_file = models.FileField(upload_to='stickers', blank=True)
    sticker_file = models.FileField(upload_to='towit/stickers', blank=True, 
                                    storage=gd_storage)
    sticker_note = models.TextField(blank=True)
    
    def get_absolute_url(self):
        return reverse('trailer_detail', kwargs={'id': self.id})
    
    def __str__(self):
        return self.name

class TrailerPicture(models.Model):
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='trailer_picture')
    # image = models.ImageField(upload_to='pictures')
    image = models.ImageField(upload_to='towit/pictures', storage=gd_storage)
    
    def get_absolute_url(self):
        return reverse('trailer_detail', kwargs={'id': self.trailer.id}) + '#gallery'

class Maintenance(models.Model):
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='trailer_maintenance')
    date =  models.DateField()
    price = models.IntegerField()
    status = models.ForeignKey(MaintenanceStatus,
                            on_delete=models.CASCADE,
                            related_name='maintenance_status')
    comments = models.TextField(blank=True)
    
    def get_absolute_url(self):
        return reverse('maintenances', kwargs={'trailer_id': self.trailer.id})
    

class Person(models.Model):
    name = models.CharField(max_length=150)
    address  = models.CharField(max_length=500, blank=True)
    mail  = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    
    
    def __str__(self):
        return self.name
 
class Lessee(Person):    
    insurance_number = models.CharField(max_length=150, blank=True)
    insurance_file = models.FileField(upload_to='towit/insurances', 
                                      storage=gd_storage, blank=True)
    license_number = models.CharField(max_length=150, blank=True)
    license_file = models.FileField(upload_to='towit/licenses', 
                                    storage=gd_storage, blank=True)    
    
    def __str__(self):
        return self.name    
    
    def get_absolute_url(self):
        return reverse('new_contract', kwargs={'lessee_id': self.lessee.id})
 
class Contact(Person): 
    interest = models.ForeignKey(Interest,
                            on_delete=models.CASCADE,
                            related_name='contact_interest')    
    size = models.IntegerField(blank=True)   
    price = models.IntegerField(blank=True)
    term = models.IntegerField()
    term_unit = models.PositiveSmallIntegerField(
        choices=((1,'Weeks'),
                (2,'Months')),
        default=1,
    )
    type = models.ForeignKey(TrailerType, blank=True, 
                            on_delete=models.CASCADE,
                            related_name='contact_type')
    interest_date =  models.DateField()
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('contact_detail', kwargs={'id': self.id})
 
class Lease(models.Model):
    lessee = models.ForeignKey(Lessee,
                            on_delete=models.CASCADE,
                            related_name='lease')   
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='lease_trailer')
    stage = models.ForeignKey(LeaseStage,
                            on_delete=models.CASCADE,
                            related_name='lease_stage')      
    location = models.CharField(max_length=500)
    location_file = models.FileField(upload_to='towit/locations', blank=True,
                                     storage=gd_storage)    
    effective_date = models.DateField()
    contract_end_date = models.DateField()
    number_of_payments = models.IntegerField()
    payment_amount = models.IntegerField()
    service_charge = models.IntegerField()
    security_deposit = models.IntegerField()
    inspection_date = models.DateField()
    current_condition = models.PositiveSmallIntegerField(
        choices=((1,'New'),
                (2,'Like new'),
                (3,'Used')),
        default=1,
    )
    
    def __str__(self):
        return self.trailer.name + " -> " + self.lessee.name
    
    class Meta:
        ordering = ('-effective_date',)
    
    def get_absolute_url(self):
        return reverse('contract_detail', kwargs={'id': self.id})    
    

class ContractDocument(models.Model):
    lease = models.ForeignKey(Lease,
                            on_delete=models.CASCADE,
                            related_name='contract_document')    
    document = models.FileField(upload_to='towit/contracts', storage=gd_storage)
    
    def get_absolute_url(self):
        return reverse('contract_detail_signed', kwargs={'id': self.lease.id})

trailer_rental/towit/templates/towit/client/base_form_clients.html
{% extends 'towit/base_form.html' %}
               
{% block nav %}
    <li><a href="/towit/contacts/">Contacts</a></li>
{% endblock %}  

trailer_rental/towit/templates/towit/client/contact.html
{% extends 'towit/base.html' %}

{% load static %}

	           
{% block nav %}
    <li><a href="/towit/trailers/">Trailers</a></li>
    <li><a href="/towit/contacts/">Contacts</a></li>
{% endblock %} 

{% block content %}    
    <h3 class="mt-3"> <b> Contacto </b>
    
      <a href="tel:{{ contact.phone }}">
        <button class="btn btn-success data-toggle="tooltip" data-placement="left" title="Call contact"">
            <i class="fa fa-phone"></i>
        </button>
      </a>
      <a href="/towit/update_contact/{{ contact.id }}">
        <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Edit contact"">
            <i class="fa fa-pencil"></i>
        </button>
      </a>
      <a href="/towit/new_lessee/{{ contact.id }}">
        <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Rent a trailer"">
            RENT
        </button>
      </a>
      <a href="/towit/delete_contact/{{ contact.id }}">
        <button class="btn btn-danger float-right data-toggle="tooltip" data-placement="left" title="Delete contact"">
            <i class="fa fa-trash"></i>
        </button>
      </a>
    </h3>    
    <hr class="mt-0 mb-4">
    <div class="card">
        <div class="card-header">
		    <div class="row"> 
		        <h4>{{ contact.name }}</h4>
		    </div>
		    <div class="row"> 
		        <a href="mailto:{{ contact.mail }}">{{ contact.mail }}</a>
		    </div>
        </div>
        <div class="card-body">
		    <div class="row"> 
		        <div class="col-4">Interest: <b>{{ contact.interest }}</b></div>
		        <div class="col-4"><b>{{ contact.interest_date }}</b></div>
		        <div class="col-4">Term: <b>{{ contact.term }} {{ contact.get_term_unit_display }}</b></div>
		    </div>
		    <div class="row" style="margin-bottom: 1em;"> 
		        <div class="col-4">Type: <b>{{ contact.type }}</b></div>
		        <div class="col-4">Size <b>{{ contact.size }}'</b></div>
		        <div class="col-4">Price: <b>${{ contact.price }}</b></div>
		    </div>
		    <div class="row text-center"> 
		        Address: {{ contact.address }}
		    </div>
        </div>
    </div>
    
    
{% endblock %} 

trailer_rental/towit/templates/towit/client/contacts.html
{% extends 'towit/dataTableBase.html' %}

{% load static %}

{% block table_head %}
{% endblock %} 
               
{% block table_params %}
    "order": [[ 5, "desc" ]],
{% endblock %} 
                
{% block nav %}
    <li><a href="/towit/trailers/">Trailers</a></li>
{% endblock %} 
	
{% block content %}
    <h3 class="mt-3">
        Contacts
        <a href="/towit/new_contact/">
		    <div class="circle">
		        <div class="circle-plus">
		            <div class="vertical-plus"> 
		            </div>  
		        </div>
		    </div>
		</a>
    </h3>
    
    <hr class="mt-0 mb-4">
    
    <div class="table-responsive-md">   
		<table id="table" class="table table-striped table-bordered table-sm" cellspacing="10" width="100%">
		  <thead>
		    <tr>
		      <th class="th-sm">Name
              </th>
              <th class="th-sm">Interest
              </th>
              <th class="th-sm">type
              </th>
              <th class="th-sm">term
              </th>
              <th class="th-sm">price
              </th>
              <th class="th-sm">date
              </th>
            </tr>
          </thead>
          <tbody>
            {% for contact in contacts %}
                <tr>
                  <td> 
                    <a class="trailer-link" href="/towit/contact/{{ contact.id }}">{{ contact.name }}</a>
                  </td>       
                  <td> {{ contact.interest }}</td>  
                  <td> {{ contact.type }} {{ contact.size }}' </td>    
                  <td> {{ contact.term }} {{ contact.get_term_unit_display }} </td>           
                  <td class="text-center"> ${{ contact.price }}</td>
                  <td class="text-center"> {{ contact.interest_date|date:"Y/m/d" }}</td>
		        </tr>	    
	        {% endfor %}
		  </tbody>
		</table>
	</div>
{% endblock %} 

trailer_rental/towit/templates/towit/client/new_contact.html
{% extends 'towit/client/base_form_clients.html' %}

{% block nav %}
    <li><a href="/towit/contacts/">Contacts</a></li>
    <li><a href="/towit/trailers/">Trailers</a></li>
{% endblock %}  

{% block title %}
        Register a new contact 
{% endblock %}

trailer_rental/towit/templates/towit/client/new_lessee.html
{% extends 'towit/client/base_form_clients.html' %}

{% block nav %}
    <li><a href="/towit/contacts/">Contacts</a></li>
    <li><a href="/towit/trailers/">Trailers</a></li>
{% endblock %}  

{% block title %}
        Lessee data 
        <a href="/towit/contacts/">
            <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Rent a trailer"">
	            Select contact
	        </button>
        </a>
{% endblock %}

trailer_rental/towit/templates/towit/client/update_contact.html
{% extends 'towit/client/base_form_clients.html' %}


{% block nav %}
    <li> 
        <a href="/towit/contact/{{ contact.id }}">
            <button class="btn btn-primary float-right">
                <i class="fa fa-arrow-left"></i>
            </button>
        </a>
    </li>
    <li>
        <button type="submit" form="update-form"  style="margin-left:1em;" 
        class="btn btn-success text-right">Save</button>
    </li>
{% endblock %}  

{% block title %}
        Edit contact 
{% endblock %}