trailer_rental/towit/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from towit.views import *
from towit.view.tracker import (
    trackers,
    tracker_data, TrackerCreateView,
    TrackerUpdateView,
    tracker_detail_n, delete_tracker,
    trackers_data,
    get_tracker_data,
    tracker_upload,
    get_tracker_upload,
    tracker_detail,
    tracker_export,
    tracker_debug,
    debug_detail,
    trackers_table)

urlpatterns = [
    # Entry point
    path('', dashboard, name='dashboard'),
    path('dashboard/',  dashboard, name='dashboard'),
    # Trailer
    path('new_trailer/',  TrailerCreateView.as_view(), name='new_trailer'),
    path('update_trailer/<slug:pk>',
         TrailerUpdateView.as_view(), name='update_trailer'),
    path('trailers/',  trailers, name='trailers'),
    path('trailer/<int:id>',  trailer_detail, name='trailer_detail'),
    path('delete_trailer/<int:id>',  delete_trailer, name='delete_trailer'),
    path('trailer_json/<int:id>',  trailer_json, name='trailer_json'),
    # Maintenance
    path('new_maintenance/<int:trailer_id>',
         MaintenanceCreateView.as_view(), name='new_maintenance'),
    path('update_maintenance/<slug:pk>',
         MaintenanceUpdateView.as_view(), name='update_maintenance'),
    path('maintenances/<int:trailer_id>',  maintenances, name='maintenances'),
    # Trailer pictures
    path('new_picture/<int:trailer_id>',
         TrailerPictureCreateView.as_view(), name='new_picture'),
    path('share_images/<ids>',  share_images, name='share_images'),
    path('delete_trailer_images/<ids>',
         delete_trailer_images, name='delete_trailer_images'),
    # Contacts
    path('new_contact/',  ContactCreateView.as_view(), name='new_contact'),
    path('contact/<int:id>',  contact_detail, name='contact_detail'),
    path('update_contact/<slug:pk>',
         ContactUpdateView.as_view(), name='update_contact'),
    path('contacts/',  contacts, name='contacts'),
    # Lessee
    path('new_lessee/<int:contact_id>',  LesseeCreateView.as_view(),
         name='new_lessee_from_contact'),
    path('new_lessee/trailer/<int:trailer_id>',
         LesseeCreateView.as_view(), name='new_lessee_from_trailer'),
    path('new_lessee/',  LesseeCreateView.as_view(), name='new_lessee'),
    # Contracts
    path('new_contract/<int:lessee_id>/',
         LeaseCreateView.as_view(), name='new_contract'),
    path('contract/<int:id>',  contract_detail, name='contract_detail'),
    path('contract_signed/<int:id>',  contract_detail_signed,
         name='contract_detail_signed'),
    path('upload_contract_document/<int:id>',
         ContractDocumentCreateView.as_view(), name='upload_contract_document'),
    path('contracts/',  contracts, name='contracts'),
    path('update_contract/<slug:pk>',
         ContractUpdateView.as_view(), name='update_contract'),
    path('delete_contract/<slug:id>',  delete_contract, name='delete_contract'),
    path('change_contract_stage/<slug:id>/<int:stage>',
         change_contract_stage, name='change_contract_stage'),
    path('capture_signature/<int:lease_id>/<position>',
         HandWritingCreateView.as_view(), name='capture_signature'),
    # Tracker
    path('new_tracker/<int:trailer_id>',
         TrackerCreateView.as_view(), name='new_tracker'),
    path('update_tracker/<slug:pk>',
         TrackerUpdateView.as_view(), name='update_tracker'),
    path('delete_tracker/<int:id>',  delete_tracker, name='delete_tracker'),
    path('tracker_detail/<int:id>',  tracker_detail, name='tracker_detail'),
    path('tracker_detail/<int:id>/<int:n>',
         tracker_detail_n, name='tracker_detail_n'),
    path('trackers_map/',  trackers, name='trackers'),
    path('trackers/',  trackers_table, name='trackers_table'),
    path('trackers_map/data', trackers_data, name='trackers_json'),
    path('tracker_data', tracker_data, name='tracker_data'),
    path('get_tracker_data/<int:id>', get_tracker_data, name='get_tracker_data'),
    path('tracker_debug', tracker_debug, name='tracker_debug'),
    path('debug_detail/<int:id>',  debug_detail, name='debug_detail'),
    path('upload_data', tracker_upload, name='upload_data'),
    path('get_upload_data/<int:id>', get_tracker_upload, name='get_upload_data'),
    path('tracker_export/<int:id>', tracker_export, name='tracker_export'),
]

trailer_rental/trailer_rental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('contracts/', include('contracts.urls')),
    path('towit/', include('towit.urls')),
]

trailer_rental/towit/models.py
from django.db import models
from datetime import datetime
from gdstorage.storage import GoogleDriveStorage
from django.urls import reverse
from django.contrib.auth.models import User

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

class UserProfile(models.Model):
    user   = models.OneToOneField(User,
                        on_delete=models.CASCADE,
                        related_name='profile_user')
    avatar = models.ImageField(upload_to='avatars')
    # avatar = models.ImageField(upload_to='towit/avatars', storage=gd_storage)
    def __str__(self):
        return self.user.get_username()

class Owners(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=7, blank=True)
    
    def __str__(self):
        return self.name
    
class TrailerType(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Status(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Interest(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class LeaseStage(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class MaintenanceStatus(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Stage(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Trailer(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(TrailerType,
                            on_delete=models.CASCADE,
                            related_name='trailer_type')
    vin = models.CharField(max_length=50)
    year = models.DateField(default=datetime.now().strftime(("%Y")))
    size = models.IntegerField()
    number_of_axles = models.PositiveSmallIntegerField(
        choices=((1,'2'),
                (2,'3')),
        default=1,
    )
    color = models.ForeignKey(Color,
                            on_delete=models.CASCADE,
                            related_name='trailer_color')
    status = models.ForeignKey(Status,
                            on_delete=models.CASCADE,
                            default = 1,
                            related_name='trailer_status')
    bed_type = models.PositiveSmallIntegerField(
        choices=((1,'Wood'),
                (2,'Steel')),
        default=1,
    )
    bed_comments = models.TextField(blank=True)
    current_tires_condition = models.PositiveSmallIntegerField(
        choices=((1,'100%'),
                (2,'75%'),
                (3,'50%')),
        default=1,
    )
    tire_layers = models.PositiveSmallIntegerField(
        choices=((1,'10'),
                (2,'14'),
                (3,'16')),
        default=1,
    )
    has_spare_tire = models.PositiveSmallIntegerField(
        choices=((1,'Yes'),
                (2,'No')),
        default=1,
    )
    number_of_ramps = models.IntegerField()
    ramps_material = models.PositiveSmallIntegerField(
        choices=((1,'Aluminium'),
                (2,'Steel')),
        default=1,
    )
    ramps_length = models.PositiveSmallIntegerField(
        choices=((1,'5'),
                (2,'6'),
                (3,'7'),
                (4,'8'),
                (5,'9')),
        default=1,
    )
    electrical_instalation = models.TextField(blank=True)
    price = models.IntegerField()
    tax_price = models.IntegerField()
    tax = models.PositiveSmallIntegerField(
        choices=((1,6.25),
                (2,8.5)),
        default=1,
    )
    owner = models.ForeignKey(Owners,
                            on_delete=models.CASCADE,
                            related_name='trailer_owner')
    Legal_owner = models.ForeignKey(Owners,
                            on_delete=models.CASCADE,
                            related_name='trailer_legal_owner')
    plate = models.CharField(max_length=50)
    plate_stage = models.PositiveSmallIntegerField(
        choices=((1,'Temporary'),
                (2,'Permanent')),
        default=1,
    )
    plate_file = models.FileField(upload_to='towit/plates', blank=True, 
                                  storage=gd_storage) 
    title = models.ForeignKey(Stage,
                            on_delete=models.CASCADE,
                            related_name='title_stage')
    # title_file = models.FileField(upload_to='titles', blank=True)
    title_file = models.FileField(upload_to='towit/titles', blank=True, 
                                  storage=gd_storage)
    title_note = models.TextField(blank=True)
    sticker = models.ForeignKey(Stage,
                            on_delete=models.CASCADE,
                            related_name='sticker_stage')
    # sticker_file = models.FileField(upload_to='stickers', blank=True)
    sticker_file = models.FileField(upload_to='towit/stickers', blank=True, 
                                    storage=gd_storage)
    sticker_note = models.TextField(blank=True)
    
    def get_absolute_url(self):
        return reverse('trailer_detail', kwargs={'id': self.id})
    
    def __str__(self):
        return self.name

class TrailerPicture(models.Model):
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='trailer_picture')
    # image = models.ImageField(upload_to='pictures')
    image = models.ImageField(upload_to='towit/pictures', storage=gd_storage)
    
    def get_absolute_url(self):
        return reverse('trailer_detail', kwargs={'id': self.trailer.id}) + '#gallery'

class Maintenance(models.Model):
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='trailer_maintenance')
    date =  models.DateField()
    price = models.IntegerField()
    status = models.ForeignKey(MaintenanceStatus,
                            on_delete=models.CASCADE,
                            related_name='maintenance_status')
    comments = models.TextField(blank=True)
    
    def get_absolute_url(self):
        return reverse('maintenances', kwargs={'trailer_id': self.trailer.id})
    

class Person(models.Model):
    name = models.CharField(max_length=150)
    address  = models.CharField(max_length=500, blank=True)
    mail  = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    
    
    def __str__(self):
        return self.name
 
class Lessee(Person):    
    insurance_number = models.CharField(max_length=150, blank=True)
    insurance_file = models.FileField(upload_to='towit/insurances', 
                                      storage=gd_storage, blank=True)
    license_number = models.CharField(max_length=150, blank=True)
    license_file = models.FileField(upload_to='towit/licenses', 
                                    storage=gd_storage, blank=True)    
    
    def __str__(self):
        return self.name    
    
    def get_absolute_url(self):
        return reverse('new_contract', kwargs={'lessee_id': self.lessee.id})
 
class Contact(Person): 
    interest = models.ForeignKey(Interest,
                            on_delete=models.CASCADE,
                            related_name='contact_interest')    
    size = models.IntegerField(blank=True)   
    price = models.IntegerField(blank=True)
    term = models.IntegerField()
    term_unit = models.PositiveSmallIntegerField(
        choices=((1,'Weeks'),
                (2,'Months')),
        default=1,
    )
    type = models.ForeignKey(TrailerType, blank=True, 
                            on_delete=models.CASCADE,
                            related_name='contact_type')
    interest_date =  models.DateField()
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('contact_detail', kwargs={'id': self.id})
 
class Lease(models.Model):
    lessee = models.ForeignKey(Lessee,
                            on_delete=models.CASCADE,
                            related_name='lease')   
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='lease_trailer')
    stage = models.ForeignKey(LeaseStage,
                            on_delete=models.CASCADE,
                            related_name='lease_stage')      
    location = models.CharField(max_length=500)
    location_file = models.FileField(upload_to='towit/locations', blank=True,
                                     storage=gd_storage)    
    effective_date = models.DateField()
    contract_end_date = models.DateField()
    number_of_payments = models.IntegerField()
    payment_amount = models.IntegerField()
    service_charge = models.IntegerField()
    security_deposit = models.IntegerField()
    inspection_date = models.DateField()
    current_condition = models.PositiveSmallIntegerField(
        choices=((1,'New'),
                (2,'Like new'),
                (3,'Used')),
        default=1,
    )
    
    def __str__(self):
        return self.trailer.name + " -> " + self.lessee.name
    
    class Meta:
        ordering = ('-effective_date',)
    
    def get_absolute_url(self):
        return reverse('contract_detail', kwargs={'id': self.id})    
    

class ContractDocument(models.Model):
    lease = models.ForeignKey(Lease,
                            on_delete=models.CASCADE,
                            related_name='contract_document')    
    document = models.FileField(upload_to='towit/contracts', storage=gd_storage)
    
    def get_absolute_url(self):
        return reverse('contract_detail_signed', kwargs={'id': self.lease.id})

trailer_rental/towit/templates/towit/contract/contract_body.html
   <p class="center"><strong>EQUIPMENT</strong><strong> LEASE</strong></p>

   <p>This Equipment Lease ("this lease") is made effective as
    of <mark>{{ contract.effective_date|date:'F d, Y' }}</mark> between Daniel Hernández Duarte and Jose Ariel Casanova ("the Lessors"), 6514 Mohave Ln, Richmond, TX 77469, 
    and <mark>{{ contract.lessee.name }}</mark>, ("the Lessee"), <mark>{{ contract.lessee.address }}</mark> and states the agreement of the parties as follows:</p>
   <p><strong>EQUIPMENT SUBJECT TO LEASE</strong>. The Lessor shall lease the equipment listed on the attached exhibit "A".</p>
   <p><strong>PAYMENT TERMS</strong>. The Lessee shall make <mark>{{ contract.number_of_payments }}</mark> payment(s) of $<mark>{{ contract.payment_amount }}</mark>. 
   The lease payments shall be due whether or not the Lessee has received notice of payment due.</p>
   <p><strong>SERVICE CHARGE</strong>. If any lease installment is not paid within 7 day(s) after the due date, 
   the Lessee shall pay to the Lessor a service charge of $<mark>{{ contract.service_charge }}</mark> for every week the payment is late.</p>
   <p><strong>SECURITY DEPOSIT</strong>. In addition to the Lease payment charge, the Lessee shall pay a security deposit of 
   $<mark>{{ contract.security_deposit }}</mark> at the time that this Lease is signed. Any amount refundable to the Lessee shall 
   be paid at the time this Lease is terminated, subject to the option of the Lessor to apply it against Lease charges and damages. 
   This security deposit shall not bear interest.</p>
   <p><strong>LEASE TERM</strong>. This Lease shall begin on the above effective date and shall terminate on <mark>{{ contract.contract_end_date|date:'F d, Y' }}</mark>, 
   unless otherwise terminated in a manner consistent with the terms of this Lease.</p>
   <p><strong>LOCATION OF EQUIPMENT</strong>. The equipment shall be located at <mark>{{ contract.location }}</mark>, during the Lease term, and shall not be 
   removed from that location without the Lessor prior written consent.</p>
   <p><strong>CARE AND OPERATION OF EQUIPMENT</strong>. The equipment may only be used and operated in a careful and proper manner. 
   Its use must comply with all laws, ordinances, and regulations relating to the possession, use, or maintenance of the equipment, 
   including registration and/or licensing requirements, if any.</p>
   <p><strong>MAINTENANCE AND REPAIR</strong>. The Lessee shall maintain, at the Lessee's cost, the equipment in good repair and operating 
   condition. Allowing for reasonable wear and tear. Such cost shall include labor, materials, parts, and similar items.</p>
   <ol><li>Tires/Brakes shall be returned new at the end of the Lease term.</li></ol>
   <p><strong>LESSOR'S RIGHT OF INSPECTION</strong>. The Lessor shall have the right to inspect the equipment during Lessee's normal business hours.</p>
   <p><strong>RETURN OF EQUIPMENT</strong>. At the end of the Lease term, the Lessee shall be obligated to return the equipment to the Lessors at the Lessee's expense.</p>
   <p><strong>OPTION TO RENEW</strong>. If the Lessee is not in default upon expiration of this Lease, 
   The Lessee shall have the option to renew this Lease for a similar term on such terms as the parties may agree at the time of such renewal.</p>
   <p><strong>OPTION TO PURCHASE</strong>. If the Lessee is not in default under this Lease, 
   the Lessees shall have the option to purchase items of equipment at the end of the lease term for the price specified for such items 
   of the equipment in the attached Equipment Schedule. The Lessee shall exercise this option by providing written notice to the Lessor of such intent at 
   least 60 day(s) prior to the end of the Lease term.</p>
   <p><strong>ACCEPTANCE OF EQUIPMENT</strong>. The Lessee shall inspect each 
   item of equipment delivered pursuant to this Lease. The Lessee shall immediately notify the Lessors of any discrepancies between 
   such items of equipment and description of the equipment in the Equipment Schedule. If the Lessee fails to provide such notice in writing within 7 day(s) after the deliver
   y of the equipment, the Lessee will be conclusively presumed to have accepted equipment as a specific in Equipment Schedule.</p>
   <p><strong>OWNERSHIP AND STATUS OF EQUIPMENT</strong>. The equipment will be deemed to be personal property, regardless of the manner in which it may 
   be attached to any other property. The Lessor shall be deemed to have retained title to the equipment at all times, unless the Lessor transferred the 
   title by sell. The Lessee shall immediately advise the Lessor regarding any notice of any claims, levy, lien, or legal process issued against equipment.</p>
   <p><strong>RISK OF LOSS OR DAMAGE</strong>. The Lessee assumes all risk of loss or damage to the equipment from any cost, 
   and agrees to return it to the Lessor in the condition received from the Lessor, with the exception of normal wear and tear, unless otherwise provided in this Lease.</p>
   <p><strong>INDEMNITY OF LESSOR FOR LOSS OR DAMAGE</strong>. Unless otherwise stated in this Lease, if the equipment is damaged or lost, 
   the Lessor shall have the option of requiring the Lessee to repair the equipment to a state of good working order, 
   or replace the equipment with like equipment in good repair, which equipment shall become the property of the Lessor and subject to this Lease.</p>
   <p><strong>LIABILITY AND INDEMNITY</strong>. Liability for injury, disability, and death of workers and other persons caused by operating, handling, 
   or transporting the equipment during the term of this lease is the obligation of the Lessee, and the Lessee shall indemnify and hold the Lessor harmless 
   from on against all such liability. Lessee shall maintain liability insurance of at least $14,000.</p>
   <p><strong>CASUALTY INSURANCE</strong>. The Lessee shall insure the equipment in an amount sufficient to cover the replacement cost of the equipment.</p>
   <p><strong>DEFAULT</strong>. The occurrence of any of the following shall constitute a default under this Lease:</p>
   <ol><li>The failure to make a required payment under this Lease when due.</li>
   <li>The violation of any other provision or requirement that is not corrected within 30 day(s) after written notice of the violation is given.</li>
   <li>The insolvency or bankruptcy of the Lessee.</li>
   <li>The subjection of any of Lessee's property to any levy, seizure, assignment, application, or sale for or by any creditor or government agency.</li></ol>
   <p><strong>RIGHTS ON DEFAULT</strong>. In addition to any other rights afforded the Lessor by law, if the Lessee is in default under this Lease, 
   without notice to or demands on the Lessee, the Lessor may take possession of the equipment as provided by law, deduct the cost of recovery (including atto
   rney fees and legal costs), repairs, and related cost, and hold the Lessee responsible for any deficiency. The rights and remedies of the 
   Lessor provided by law and this Agreement shall be cumulative in nature. The Lessor shall be obligated to re-lease the equipment, 
   or otherwise mitigate the damage from the default, only as required by law.</p>
   <p><strong>NOTICE</strong>. All notices required or permitted under this Lease shall be deemed delivered when delivered in person or by mail, postage 
   prepaid, addressed to the appropriate party at the address shown for that party at the beginning of this Lease.</p>
   <p><strong>ASSIGNMENT</strong>.  The Lessee shall not assign or sublet any interest in this Lease or the equipment or permit the equipment to be used 
   by anyone other than the Lessee or the Lessee's employees, without Lessors prior written consent.</p>
   <p><strong>ENTIRE AGREEMENT AND MODIFICATION</strong>. This Lease constitutes the entire agreement between the parties. 
   No modification or amendment of this Lease shall be effective unless in writing and signed by both parties. This Lease replaces any all-prior agreement between the parties.</p>
   <p><strong>COVERING LAW</strong>.  This Lease shall be construed in accordance with the laws of the state of Texas.</p>
   <p><strong>SEVERABILITY</strong>. If any portion of this Lease shall be held to be invalid or unenforceable by any reason, 
   the remaining provisions shall continue to be valid and enforceable. If a court finds that any provision of this Lease is invalid or unenforceable, 
   but that by limiting such provisions, it would become valid and enforceable, then such provision shall be deemed to be written, construed, and enforced as so limited.</p>
   <p><strong>WAIVER</strong>. The failure of either party to enforce any provision of this lease shall not be construed as a waiver or limitation of the
    party's right to subsequently enforce and compel strict compliance with every provision of this Lease.</p>
   <p><strong>CERTIFICATION</strong>. Lessee certifies that the application, statement, trade reference and financial reports to make it to the Lessor ar
   e true and correct and any material misrepresentation will constitute a default under this Lease.</p>
   <p><strong>DISPUTE RESOLUTION</strong>. The parties will attempt to resolve any dispute arising out of the relating to this Agreement through friendly
    negotiations among the parties. If the matter is not resolved by negotiation, 
    the parties will resolve the dispute using the below Alternative Dispute Resolution (ADR) procedure.</p>
   <p>Any controversies or disputes arising out of or relating to this Agreement will be submitted to mediation in accordance with any statutory rules or mediation. 
   If mediation is not successful in resolving the entire dispute or is unavailable, 
   any outstanding issues will be submitted to final and binding arbitration under the rules of the American Arbitration Association. 
   The arbitrator's award will be final, and judgment may be entered upon it by any court having proper jurisdiction.</p>
   <p><strong>SIGNATORIES</strong>. This Lease shall be signed by Daniel Hernández Duarte, Jose Ariel Casanova and <mark>{{ contract.lessee.name }}</mark> and shall be effective
    as of the date first above written.</p>

trailer_rental/towit/templates/towit/contract/contract_detail.html
{% extends 'towit/base.html' %}

{% block head %}
   <meta charset="utf-8"/>
   <style>
    {% block mark %}    
      mark { 
         background-color: yellow;
         color: black;
      }
    {% endblock %}
     .bottom-three-left-two {
         margin-left: 3em;
         margin-top: -4em;
         z-index:-1;
     }
     
    .date_btn {
        margin-left: 3.5em;
    }
     
    .date {
        margin-bottom: 2em;
        max-width: 300px;
    }
     
    .signature_btn {
        margin-left: 4em;
        margin-right: 3em;
    }
     
	.signature {
	    margin-bottom: 2.5em;
        max-width: 350px;
        z-index:1;
	}
     .center {
	      text-align: center;
      }
      p, li {
	      text-align: justify;
      }
      div.break {
         page-break-before:always;
      }
    .left-space {
        margin-left: 1em;
        margin-right: 0.5em;
    }
   </style>
    <script>
       function deleteContract() {
            let confirmAction = confirm("Are you sure to delete the current contract?");
            if (confirmAction) {
                 window.location = "/towit/delete_contract/{{ contract.id }}";
            }
        }
       function approveContract() {
            let confirmAction = confirm("Are you sure to approve the contract? A pdf copy will be send to the lessee.");
            if (confirmAction) {
                 window.location = "/towit/change_contract_stage/{{ contract.id }}/2";
            }
        }
       function finishContract() {
            let confirmAction = confirm(`Are you sure to finish the contract? 
                                        A signed copy will be send to the lessee.
                                        An event will be added to the calendar.`);
            if (confirmAction) {
                 window.location = "/towit/change_contract_stage/{{ contract.id }}/3";
            }
        }
       function archiveContract() {
            let confirmAction = confirm(`Are you sure to finish the contract? 
                                        A signed copy will be send to the lessee.
                                        An event will be added to the calendar.`);
            if (confirmAction) {
                 window.location = "/towit/change_contract_stage/{{ contract.id }}/5";
            }
        }
    </script>
{% endblock %}
                
{% block nav %}
    <li> 
        <a href="/towit/update_contract/{{ contract.id }}">
            <button class="btn btn-primary">
                <i class="fa fa-pencil"></i>
            </button>
        </a>
    </li>
    <li> 
        {% if contract.stage.id == 1 %}
	        <button onclick="approveContract()" class="btn btn-primary left-space">
	            Approve
	        </button>
	    {% else %}
	        {% if contract.stage.id == 2 %}
	            <button onclick="finishContract()" class="btn btn-primary left-space">
	                Finish
	            </button>
                <a href="/towit/upload_contract_document/{{ contract.id }}">
	                <button class="btn btn-primary left-space">
	                    Upload
	                </button>
	            </a>
	        {% else %}
                <button onclick="archiveContract()" class="btn btn-primary left-space">
                    Archive
                </button>
	        {% endif %}
	    {% endif %}
    </li>
    <li> 
		<button onclick="deleteContract()" class="btn btn-danger  left-space data-toggle="tooltip" data-placement="left" title="Delete contract"">
		    <i class="fa fa-trash"></i>
		</button>
    </li>
{% endblock %}  

{% block content %}
    {% include 'towit/contract/contract_body.html' %}
    
    {% include 'towit/contract/signatures_and_date.html' %}


   <div class="break"></div>
   <p class="center"><strong>EXHIBIT A</strong></p>
   <p><strong>Equipment Schedule</strong></p>
   <p>Equipment Description: <mark>{{ contract.trailer.type }} {{ contract.trailer.size }}'</mark> VIN:<mark>{{ contract.trailer.vin }}</mark></p>
   <p>Lease End Purchase Price: Market Price </p>
   <p>Email: <mark>{{ contract.lessee.mail }}</mark></p>

    {% include 'towit/contract/trailer_condition_report.html' %}  
   
    
    {% include 'towit/contract/signatures_and_date.html' %}
   
   
{% endblock %} 

trailer_rental/towit/templates/towit/contract/new_contract.html
{% extends 'towit/base_form.html' %}

{% block form_head %}
    <script>
        jQuery(document).ready(function(){
		    $('#id_trailer').on('change', function() {
	          $.getJSON( "/towit/trailer_json/"+this.value, function( data ) {
               let specs = `
               <div class="row">
	               <div class="col-6">
	                   Trailer type: <b>` + data.type +" "+ data.size +`'</b>
	               </div>
                   <div class="col-6">
                    Number of axles: <b>` + data.number_of_axles +`</b>
                   </div>
               </div>
               <div class="row">
                   <div class="col-6">
                       Has spare tire: <b>` + data.has_spare_tire +`</b>
                   </div>
                   <div class="col-6">
                    Current tires condition: <b>` + data.current_tires_condition +`</b>
                   </div>
               </div>
               <div class="row">
	               <div class="col-6 card">
	                   <div class="card-header">
	                       Bed type: <b>` + data.bed_type +`</b>
	                   </div>
	                   <div class="card-body">
	                    ` + data.bed_comments +`</b>
	                   </div>
	               </div>
	               <div class="col-6 card">
	                   <div class="card-header">
	                       Electrical instalation
	                   </div>
	                   <div class="card-body">
	                    ` + data.electrical_instalation +`</b>
	                   </div>
	               </div>
               </div>
               <div class="row">
                The trailer has &nbsp<b>` + data.number_of_ramps +" "+ 
                data.ramps_material +` </b>&nbsp ramps, &nbsp<b>`+ 
                data.ramps_length +`</b>&nbsp feet long each.</div>
               </div>
               <hr class="mt-0 mb-4">
               `
				$("#id_trailer_conditions").html(specs);
				});
			});
        });
    </script>
{% endblock %}

{% block nav %}
    <li><a href="/towit/contacts/">Contacts</a></li>
    <li><a href="/towit/trailers/">Trailers</a></li>
{% endblock %}  

{% block title %}
        Create lease contract 
{% endblock %}