trailer_rental/towit/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from towit.views import *
from towit.view.tracker import (
    trackers,
    tracker_data, TrackerCreateView,
    TrackerUpdateView,
    tracker_detail_n, delete_tracker,
    trackers_data,
    get_tracker_data,
    tracker_upload,
    get_tracker_upload,
    tracker_detail,
    tracker_export,
    tracker_debug,
    debug_detail,
    trackers_table)

urlpatterns = [
    # Entry point
    path('', dashboard, name='dashboard'),
    path('dashboard/',  dashboard, name='dashboard'),
    # Trailer
    path('new_trailer/',  TrailerCreateView.as_view(), name='new_trailer'),
    path('update_trailer/<slug:pk>',
         TrailerUpdateView.as_view(), name='update_trailer'),
    path('trailers/',  trailers, name='trailers'),
    path('trailer/<int:id>',  trailer_detail, name='trailer_detail'),
    path('delete_trailer/<int:id>',  delete_trailer, name='delete_trailer'),
    path('trailer_json/<int:id>',  trailer_json, name='trailer_json'),
    # Maintenance
    path('new_maintenance/<int:trailer_id>',
         MaintenanceCreateView.as_view(), name='new_maintenance'),
    path('update_maintenance/<slug:pk>',
         MaintenanceUpdateView.as_view(), name='update_maintenance'),
    path('maintenances/<int:trailer_id>',  maintenances, name='maintenances'),
    # Trailer pictures
    path('new_picture/<int:trailer_id>',
         TrailerPictureCreateView.as_view(), name='new_picture'),
    path('share_images/<ids>',  share_images, name='share_images'),
    path('delete_trailer_images/<ids>',
         delete_trailer_images, name='delete_trailer_images'),
    # Contacts
    path('new_contact/',  ContactCreateView.as_view(), name='new_contact'),
    path('contact/<int:id>',  contact_detail, name='contact_detail'),
    path('update_contact/<slug:pk>',
         ContactUpdateView.as_view(), name='update_contact'),
    path('contacts/',  contacts, name='contacts'),
    # Lessee
    path('new_lessee/<int:contact_id>',  LesseeCreateView.as_view(),
         name='new_lessee_from_contact'),
    path('new_lessee/trailer/<int:trailer_id>',
         LesseeCreateView.as_view(), name='new_lessee_from_trailer'),
    path('new_lessee/',  LesseeCreateView.as_view(), name='new_lessee'),
    # Contracts
    path('new_contract/<int:lessee_id>/',
         LeaseCreateView.as_view(), name='new_contract'),
    path('contract/<int:id>',  contract_detail, name='contract_detail'),
    path('contract_signed/<int:id>',  contract_detail_signed,
         name='contract_detail_signed'),
    path('upload_contract_document/<int:id>',
         ContractDocumentCreateView.as_view(), name='upload_contract_document'),
    path('contracts/',  contracts, name='contracts'),
    path('update_contract/<slug:pk>',
         ContractUpdateView.as_view(), name='update_contract'),
    path('delete_contract/<slug:id>',  delete_contract, name='delete_contract'),
    path('change_contract_stage/<slug:id>/<int:stage>',
         change_contract_stage, name='change_contract_stage'),
    path('capture_signature/<int:lease_id>/<position>',
         HandWritingCreateView.as_view(), name='capture_signature'),
    # Tracker
    path('new_tracker/<int:trailer_id>',
         TrackerCreateView.as_view(), name='new_tracker'),
    path('update_tracker/<slug:pk>',
         TrackerUpdateView.as_view(), name='update_tracker'),
    path('delete_tracker/<int:id>',  delete_tracker, name='delete_tracker'),
    path('tracker_detail/<int:id>',  tracker_detail, name='tracker_detail'),
    path('tracker_detail/<int:id>/<int:n>',
         tracker_detail_n, name='tracker_detail_n'),
    path('trackers_map/',  trackers, name='trackers'),
    path('trackers/',  trackers_table, name='trackers_table'),
    path('trackers_map/data', trackers_data, name='trackers_json'),
    path('tracker_data', tracker_data, name='tracker_data'),
    path('get_tracker_data/<int:id>', get_tracker_data, name='get_tracker_data'),
    path('tracker_debug', tracker_debug, name='tracker_debug'),
    path('debug_detail/<int:id>',  debug_detail, name='debug_detail'),
    path('upload_data', tracker_upload, name='upload_data'),
    path('get_upload_data/<int:id>', get_tracker_upload, name='get_upload_data'),
    path('tracker_export/<int:id>', tracker_export, name='tracker_export'),
]

trailer_rental/trailer_rental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('contracts/', include('contracts.urls')),
    path('towit/', include('towit.urls')),
]

trailer_rental/towit/models.py
from django.db import models
from datetime import datetime
from gdstorage.storage import GoogleDriveStorage
from django.urls import reverse
from django.contrib.auth.models import User

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

class UserProfile(models.Model):
    user   = models.OneToOneField(User,
                        on_delete=models.CASCADE,
                        related_name='profile_user')
    avatar = models.ImageField(upload_to='avatars')
    # avatar = models.ImageField(upload_to='towit/avatars', storage=gd_storage)
    def __str__(self):
        return self.user.get_username()

class Owners(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=7, blank=True)
    
    def __str__(self):
        return self.name
    
class TrailerType(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Status(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Interest(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class LeaseStage(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class MaintenanceStatus(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Stage(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Trailer(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(TrailerType,
                            on_delete=models.CASCADE,
                            related_name='trailer_type')
    vin = models.CharField(max_length=50)
    year = models.DateField(default=datetime.now().strftime(("%Y")))
    size = models.IntegerField()
    number_of_axles = models.PositiveSmallIntegerField(
        choices=((1,'2'),
                (2,'3')),
        default=1,
    )
    color = models.ForeignKey(Color,
                            on_delete=models.CASCADE,
                            related_name='trailer_color')
    status = models.ForeignKey(Status,
                            on_delete=models.CASCADE,
                            default = 1,
                            related_name='trailer_status')
    bed_type = models.PositiveSmallIntegerField(
        choices=((1,'Wood'),
                (2,'Steel')),
        default=1,
    )
    bed_comments = models.TextField(blank=True)
    current_tires_condition = models.PositiveSmallIntegerField(
        choices=((1,'100%'),
                (2,'75%'),
                (3,'50%')),
        default=1,
    )
    tire_layers = models.PositiveSmallIntegerField(
        choices=((1,'10'),
                (2,'14'),
                (3,'16')),
        default=1,
    )
    has_spare_tire = models.PositiveSmallIntegerField(
        choices=((1,'Yes'),
                (2,'No')),
        default=1,
    )
    number_of_ramps = models.IntegerField()
    ramps_material = models.PositiveSmallIntegerField(
        choices=((1,'Aluminium'),
                (2,'Steel')),
        default=1,
    )
    ramps_length = models.PositiveSmallIntegerField(
        choices=((1,'5'),
                (2,'6'),
                (3,'7'),
                (4,'8'),
                (5,'9')),
        default=1,
    )
    electrical_instalation = models.TextField(blank=True)
    price = models.IntegerField()
    tax_price = models.IntegerField()
    tax = models.PositiveSmallIntegerField(
        choices=((1,6.25),
                (2,8.5)),
        default=1,
    )
    owner = models.ForeignKey(Owners,
                            on_delete=models.CASCADE,
                            related_name='trailer_owner')
    Legal_owner = models.ForeignKey(Owners,
                            on_delete=models.CASCADE,
                            related_name='trailer_legal_owner')
    plate = models.CharField(max_length=50)
    plate_stage = models.PositiveSmallIntegerField(
        choices=((1,'Temporary'),
                (2,'Permanent')),
        default=1,
    )
    plate_file = models.FileField(upload_to='towit/plates', blank=True, 
                                  storage=gd_storage) 
    title = models.ForeignKey(Stage,
                            on_delete=models.CASCADE,
                            related_name='title_stage')
    # title_file = models.FileField(upload_to='titles', blank=True)
    title_file = models.FileField(upload_to='towit/titles', blank=True, 
                                  storage=gd_storage)
    title_note = models.TextField(blank=True)
    sticker = models.ForeignKey(Stage,
                            on_delete=models.CASCADE,
                            related_name='sticker_stage')
    # sticker_file = models.FileField(upload_to='stickers', blank=True)
    sticker_file = models.FileField(upload_to='towit/stickers', blank=True, 
                                    storage=gd_storage)
    sticker_note = models.TextField(blank=True)
    
    def get_absolute_url(self):
        return reverse('trailer_detail', kwargs={'id': self.id})
    
    def __str__(self):
        return self.name

class TrailerPicture(models.Model):
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='trailer_picture')
    # image = models.ImageField(upload_to='pictures')
    image = models.ImageField(upload_to='towit/pictures', storage=gd_storage)
    
    def get_absolute_url(self):
        return reverse('trailer_detail', kwargs={'id': self.trailer.id}) + '#gallery'

class Maintenance(models.Model):
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='trailer_maintenance')
    date =  models.DateField()
    price = models.IntegerField()
    status = models.ForeignKey(MaintenanceStatus,
                            on_delete=models.CASCADE,
                            related_name='maintenance_status')
    comments = models.TextField(blank=True)
    
    def get_absolute_url(self):
        return reverse('maintenances', kwargs={'trailer_id': self.trailer.id})
    

class Person(models.Model):
    name = models.CharField(max_length=150)
    address  = models.CharField(max_length=500, blank=True)
    mail  = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    
    
    def __str__(self):
        return self.name
 
class Lessee(Person):    
    insurance_number = models.CharField(max_length=150, blank=True)
    insurance_file = models.FileField(upload_to='towit/insurances', 
                                      storage=gd_storage, blank=True)
    license_number = models.CharField(max_length=150, blank=True)
    license_file = models.FileField(upload_to='towit/licenses', 
                                    storage=gd_storage, blank=True)    
    
    def __str__(self):
        return self.name    
    
    def get_absolute_url(self):
        return reverse('new_contract', kwargs={'lessee_id': self.lessee.id})
 
class Contact(Person): 
    interest = models.ForeignKey(Interest,
                            on_delete=models.CASCADE,
                            related_name='contact_interest')    
    size = models.IntegerField(blank=True)   
    price = models.IntegerField(blank=True)
    term = models.IntegerField()
    term_unit = models.PositiveSmallIntegerField(
        choices=((1,'Weeks'),
                (2,'Months')),
        default=1,
    )
    type = models.ForeignKey(TrailerType, blank=True, 
                            on_delete=models.CASCADE,
                            related_name='contact_type')
    interest_date =  models.DateField()
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('contact_detail', kwargs={'id': self.id})
 
class Lease(models.Model):
    lessee = models.ForeignKey(Lessee,
                            on_delete=models.CASCADE,
                            related_name='lease')   
    trailer = models.ForeignKey(Trailer,
                            on_delete=models.CASCADE,
                            related_name='lease_trailer')
    stage = models.ForeignKey(LeaseStage,
                            on_delete=models.CASCADE,
                            related_name='lease_stage')      
    location = models.CharField(max_length=500)
    location_file = models.FileField(upload_to='towit/locations', blank=True,
                                     storage=gd_storage)    
    effective_date = models.DateField()
    contract_end_date = models.DateField()
    number_of_payments = models.IntegerField()
    payment_amount = models.IntegerField()
    service_charge = models.IntegerField()
    security_deposit = models.IntegerField()
    inspection_date = models.DateField()
    current_condition = models.PositiveSmallIntegerField(
        choices=((1,'New'),
                (2,'Like new'),
                (3,'Used')),
        default=1,
    )
    
    def __str__(self):
        return self.trailer.name + " -> " + self.lessee.name
    
    class Meta:
        ordering = ('-effective_date',)
    
    def get_absolute_url(self):
        return reverse('contract_detail', kwargs={'id': self.id})    
    

class ContractDocument(models.Model):
    lease = models.ForeignKey(Lease,
                            on_delete=models.CASCADE,
                            related_name='contract_document')    
    document = models.FileField(upload_to='towit/contracts', storage=gd_storage)
    
    def get_absolute_url(self):
        return reverse('contract_detail_signed', kwargs={'id': self.lease.id})

trailer_rental/towit/templates/towit/trailer/base_form_trailer.html
{% extends 'towit/base_form.html' %}
               
{% block nav %}
    <li><a href="/towit/trailers/">Trailers</a></li>
{% endblock %}  

trailer_rental/towit/templates/towit/trailer/maintenances.html
{% extends 'towit/dataTableBase.html' %}

{% load static %}

{% block table_head %}
{% endblock %} 
               
{% block table_params %}
    "order": [[ 1, "desc" ]],
{% endblock %} 
                
{% block nav %}
    <li><a href="/towit/trailers/">Trailers</a></li>
    <li><a href="/towit/trailer/{{ trailer.id }}">Trailer</a></li>
{% endblock %} 
	
{% block content %}
    <h3 class="mt-3">
        Maintenances
        <a href="/towit/new_maintenance/{{ trailer.id }}">
		    <div class="circle">
		        <div class="circle-plus">
		            <div class="vertical-plus"> 
		            </div>  
		        </div>
		    </div>
		</a>
    </h3>
    
    <hr class="mt-0 mb-4">
    
    <div class="table-responsive-md">   
		<table id="table" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
		  <thead>
		    <tr>
		      <th class="th-sm">Status
              </th>
              <th class="th-sm">Date
              </th>
              <th class="th-sm">Price
              </th>
              <th class="th-sm">Comments
              </th>
            </tr>
          </thead>
          <tbody>
            {% for maintenance in maintenances %}
                <tr>
                  <td> <a class="trailer-link" href="/towit/update_maintenance/{{ maintenance.id }}">{{ maintenance.status }}</a></td>
                  <td class="text-center"> {{ maintenance.date|date:"Y/m/d" }}</td>
                  <td class="text-center"> ${{ maintenance.price }}</td>
                  <td> {{ maintenance.comments }}</td>
		        </tr>	    
	        {% endfor %}
		  </tbody>
		  <tfoot>
		    <tr>
              <th class="th-sm">Status
              </th>
              <th class="th-sm">Date
              </th>
              <th class="th-sm">Price
              </th>
              <th class="th-sm">Comments
              </th>
		    </tr>
		  </tfoot>
		</table>
	</div>
{% endblock %} 

trailer_rental/towit/templates/towit/trailer/new_maintenance.html
{% extends 'towit/base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
{% endblock %}
               
{% block nav %}
    <li><a href="/towit/trailers/">Trailers</a></li>
    <li><a href="/towit/trailer/{{ trailer_id }}">Trailer</a></li>
{% endblock %}  

{% block content %}
	<h3 class="mt-3">Schedule a new Maintenance</h3>
	<hr class="mt-0 mb-4">
	<form enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-success">Shedule maintenance</button>
	</form>
{% endblock %} 

trailer_rental/towit/templates/towit/trailer/new_picture.html
{% extends 'towit/trailer/base_form_trailer.html' %}

{% block title %}
    Add trailer picture
{% endblock %}

trailer_rental/towit/templates/towit/trailer/new_tracker.html
{% extends 'towit/trailer/base_form_trailer.html' %}

{% block title %}
    Register a new tracker
{% endblock %}

trailer_rental/towit/templates/towit/trailer/trailer.html
{% extends 'towit/base.html' %}

{% load static %}
{% load tz %}

{% block head %}
    <style>
    .hidden{
        visibility: hidden;
    }
	.dot {
	  height: 1em;
	  width: 1em;
	  background-color: {{trailer.color.code}};
	  border-radius: 50%;
	  display: inline-block;
	  padding-top:5px;
	}
	.bottom-space {
	    margin-bottom: 1em;
	}

	#trigger {
	  display: none;
	}
	.checker {
        object-fit: cover;
        object-position: center;
        height: 200px;
        width: 200px;
      }
    {% for img in images %}   
		#trigger-{{ img.id }}:checked + .img-border {
		  border:3px solid blue;
		}
	{% endfor %}
    </style>
        
    <script>
    
        function getSelectedImages(){
          /* Get the text field */
          let imgs =  document.getElementsByClassName("img-cb");
        
          /* Select the text field */
          let urls = "";
          
          for (let item of imgs) {
                if(item.checked){
                    urls += item.value + ",";
                }
          }
          return urls
        }
    
        function shareImages() {  
            let imgs = getSelectedImages();
            if (imgs.length > 0){
                window.open("/towit/share_images/"+imgs, '_blank');   
            } else {
                alert("Please, select at least one picture!")
            }
        }
        
        function deletePictures() {        
            let imgs = getSelectedImages();
            if (imgs.length > 0){
				let confirmAction = confirm("Are you sure to delete the selected pictures?");
				if (confirmAction) {
				     window.location = "/towit/delete_trailer_images/"+imgs;
				}
            } else {
                alert("Please, select at least one picture!")
            }
        }
        
        function deleteTrailer() {
            let confirmAction = confirm("Are you sure to delete the current trailer?");
            if (confirmAction) {
                 window.location = "/towit/delete_trailer/{{ trailer.id }}";
            }
        }
        
        function deleteTracker() {
            let confirmAction = confirm("Are you sure to delete the tracker?");
            if (confirmAction) {
                 window.location = "/towit/delete_tracker/{{ tracker.id }}";
            }
        }
    </script>
{% endblock %} 
	           
{% block nav %}
    <li><a href="/towit/trailers/">Trailers</a></li>
{% endblock %} 

{% block content %}    
    <h3 class="mt-3">Trailer <b> {{ trailer.name }} </b>
      <a href="/towit/update_trailer/{{ trailer.id }}">
        <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Edit trailer"">
            <i class="fa fa-pencil"></i>
        </button>
      </a>      
    {% if trailer.status.name != "Rented" %}
	    <a href="/towit/new_lessee/trailer/{{ trailer.id }}">
	        <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Rent this trailer"">
	            RENT
	        </button>
	    </a>
	{% endif %}
	    <button onclick="deleteTrailer()" class="btn btn-danger float-right data-toggle="tooltip" data-placement="left" title="Delete trailer"">
	        <i class="fa fa-trash"></i>
	    </button>
    </h3>    
    <hr class="mt-0 mb-4">
    
    <!-- Tracker -->
    <h4 class="mt-3">Tracking </b>
        {% if tracker %}
            <a href="/towit/update_tracker/{{ tracker.id }}">
		        <button onclick="shareImages()" class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Copy to clipboard"">
		            <i class="fa fa-pencil"></i>
		        </button>
            </a>   
        {% else %}
	        <a href="/towit/new_tracker/{{ trailer.id }}">
	            <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Edit trailer"">
	                <i class="fa fa-plus"></i>
	            </button>
	        </a>   
	    {% endif %}
        <button onclick="deleteTracker()" class="btn btn-danger float-right data-toggle="tooltip" data-placement="left" title="Remove current picture"">
            <i class="fa fa-trash"></i>
        </button>
    </h4>  
    <hr class="mt-0 mb-4">
    {% if tracker %}
        <div class="col-12 text-center">Updated: <b> {{ tracker.last_update|localtime }} </b></div>
	    <div class="row text-center">
	       <div class="col-6 col-md-6">
	           <a href="http://maps.google.com/maps?f=q&q={{ tracker.latitude }},{{ tracker.longitude }}&z=16">
	               <i class="fa fa-map-marker"></i> 
	               lat: {{ tracker.latitude|floatformat:2 }}°, lon: {{ tracker.longitude|floatformat:2 }}° 
	           </a>
	       </div>
	      <div class="col-6 col-md-6">Credit: <b> ${{ tracker.line_credit|floatformat:2 }} </b></div>
	    </div>
    {% endif %}
    
    <!-- Specifications -->
    <h4 class="mt-3">Specifications </b></h4>  
    <hr class="mt-0 mb-4">
	<div class="row">
	  <div class="col-6 col-md-5">VIN: <b> {{ trailer.vin }} </b></div>
	  <div class="col-6 col-md-3">Size: <b> {{ trailer.size }}' </b></div>
	  <div class="col-6 col-md-4">Type: <b> {{ trailer.type }} </b></div>
	</div>
    <div class="row">
      <div class="col-6 col-md-5"><b>{{ trailer.number_of_ramps }}</b> ramps, <b>{{ trailer.get_ramps_length_display }}'</b> length</div>
      <div class="col-6 col-md-3">Axles: <b> {{ trailer.get_number_of_axles_display }} </b></div>
      <div class="col-6 col-md-4">Bed: <b> {{ trailer.get_bed_type_display }} </b></div>
    </div>
    <div class="row">
      <div class="col-6 col-md-5">Material: <b> {{ trailer.get_ramps_material_display }} </b></div>
      <div class="col-6 col-md-3">Tires: <b> {{ trailer.get_current_tires_condition_display }} </b></div>
      <div class="col-6 col-md-4">Color: <span class="dot"></span> <b> {{ trailer.color }} </b></div>
    </div>

    <!-- Legal matters -->
    <h4 class="mt-3">Legal matters </b></h4>  
    <hr class="mt-0 mb-4">
    <div class="row">
        {% load humanize %}
      <div class="col-6 col-md-5">Tax Price: <b> ${{ trailer.tax_price|intcomma }} </b></div>
      <div class="col-6 col-md-3">Tax: <b> ${{ tax|intcomma }} </b></div>
      <div class="col-6 col-md-4">Price: <b> ${{ trailer.price|intcomma }} </b></div>
    </div>
    <div class="row bottom-space">
      <div class="col-6 col-md-5">Legal owner: <b> {{ trailer.Legal_owner }} </b></div>
      <div class="col-6 col-md-3">Owner: <b> {{ trailer.owner }} </b></div>
      <div class="col-6 col-md-4">Plate: <b> {{ trailer.plate }} </b>      
        {% if trailer.plate_stage == 1 %}
           (T)
        {% endif %}
      </div>
    </div>
    <div class="row">
        <div class="col-6 card">            
            <div class="card-header">
		        Title: 
		        {% if trailer.title_file != "" %}
		            <a href="{{ trailer.title_file.url }}"><b> {{ trailer.title }} </b></a>
		        {% else %}
		            <b> {{ trailer.title }} </b>
		        {% endif %}
            </div>
			  <div class="card-body">
			        {{ trailer.title_note }}
			  </div>
        </div>   
        <div class="col-6 card">     
            <div class="card-header">
	            Sticker: 
	            {% if trailer.sticker_file != "" %}
                  <a href="{{ trailer.sticker_file.url }}"><b> {{ trailer.sticker }} </b></a>
	            {% else %}
	                <b> {{ trailer.sticker }} </b>
	            {% endif %}             
            </div>
		      <div class="card-body">
		        {{ trailer.sticker_note }}
		      </div>
        </div>    
    </div>    

    <!-- Maintenance -->
    <h4 id="maintenance_section" class="mt-3">Maintenance</b>
        <a href="/towit/maintenances/{{ trailer.id }}">
	        <button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Copy to clipboard"">
	            <i class="fa fa-wrench"></i>
	        </button>
	    </a>
    </h4>  	    
    {% if maintenance != "" %}
	    <hr class="mt-0 mb-4">
	    <div class="row card">    
	        <div class="card-header row">
                    <div class="col-6">   
                        Status:  <b> {{ maintenance.status }} </b>
	                </div>
                    <div class="col-6">  
                        {{ maintenance.date }}
                    </div>
	        </div>
			<div class="card-body">
			    {{ maintenance.comments }}
			</div>
	    </div>  
    {% endif %}  
    
    
    <!-- Gallery -->    
    <h4 id="gallery" class="mt-3">Gallery </b>
        <button onclick="shareImages()" class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Copy to clipboard"">
		    <i class="fa fa-share"></i>
	    </button>
		<a href="/towit/new_picture/{{ trailer.id }}">
			<button class="btn btn-primary data-toggle="tooltip" data-placement="left" title="Edit trailer"">
			    <i class="fa fa-plus"></i>
			</button>
		</a>   
        <button onclick="deletePictures()" class="btn btn-danger float-right data-toggle="tooltip" data-placement="left" title="Remove current picture"">
            <i class="fa fa-trash"></i>
        </button>
    </h4>  
    <hr class="mt-0 mb-4">
    <div class="row col-12">
    {% for img in images %}        
	    <div class="col-6 col-md-4 text-center">
			<input value={{ img.id }} id="trigger-{{ img.id }}" type="checkbox" style="display: none;" class="img-cb">
			<label for="trigger-{{ img.id }}" class="img-border">
			    <img class="checker" src="{{ img.image.url }}" alt="Trailer picture">
			</label>
	    </div>
    {% endfor %}
    </div>  
{% endblock %} 